version: '3'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "8080:8080"
      - "4566:4566"
    volumes:
      - ./localstack:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - SERVICES=lambda,apigateway
      - DEFAULT_REGION=ap-northeast-1
      - LAMBDA_DOCKER_NETWORK=host
      # docker-reuseではうまくいかなった
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LS_LOG=trace-internal

  postgres:
    container_name: postgres
    shm_size: '1gb'
    image: postgres:14-alpine
    ports:
      - "5431:5432"
    volumes:
      - "./data/postgres/data:/usr/local/pgsql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always